// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemindersManager.DAL;

namespace RemindersManager.Migrations
{
    [DbContext(typeof(ReminderContext))]
    [Migration("20190121004959_Init-Migration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RemindersManager.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new { Id = new Guid("f58d0b6e-23b2-4379-8b19-a939c9ef360a"), Email = "franz.kafka@gmail.com", Name = "Franz Kafka" }
                    );
                });

            modelBuilder.Entity("RemindersManager.Models.Reminder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AuthorId");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsCancelled");

                    b.Property<string>("Notes")
                        .HasMaxLength(500);

                    b.Property<DateTime>("RemindDate");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(80);

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Reminders");

                    b.HasData(
                        new { Id = new Guid("a13ab3c3-beba-404e-a87d-e681d6beaa25"), AuthorId = new Guid("f58d0b6e-23b2-4379-8b19-a939c9ef360a"), IsActive = true, IsCancelled = false, Notes = "Write clean code!", RemindDate = new DateTime(2019, 1, 18, 6, 0, 0, 0, DateTimeKind.Unspecified), Subject = "Finish interview task" }
                    );
                });

            modelBuilder.Entity("RemindersManager.Models.Reminder", b =>
                {
                    b.HasOne("RemindersManager.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");
                });
#pragma warning restore 612, 618
        }
    }
}
